baseurl = "http://www.example.com"
title = "Проектная практика 2025"
theme = "hugo-coder"
languagecode = "ru"
defaultcontentlanguage = "ru"

[params]
  avatarurl = "/images/moskovskij_politeh.png"
  author = "Совершенствование цифровой инфраструктуры для проектной деятельности"
  custom = ["scss/custom.scss"]
  info = "Исследование и внедрение современных цифровых решений для оптимизации работы над учебными проектами в Московском Политехе"
  colorScheme = "auto"
  hidecolorschemetoggle = false

[[menu.main]]
  identifier = "about"
  name = "О проекте"
  weight = 1
  url  = "/about/"

[[menu.main]]
  identifier = "participants"
  name = "Участники"
  weight = 2
  url = "/participants/"

[[menu.main]]
  identifier = "journal"
  name = "Журнал"
  weight = 3
  url  = "/journal/"

[[menu.main]]
  identifier = "resources"
  name = "Ресурсы"
  weight = 4
  url = "/resources/"